server {
    listen 80;

    # Route ALL normal requests to the front-end service
    location / {
        proxy_pass http://front-end:9000;
    }

    # Route API requests to the backend service
    location /api/ {
        proxy_pass http://back-end:5252;
    }
}
